# Form implementation generated from reading ui file 'Tagg.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from datetime import datetime

from PyQt6 import QtCore, QtGui, QtWidgets
import gerarRelatorio
import gerarEtiquetas


class Ui_JanelaTagg(object):
    def setupUi(self, JanelaTagg):
        JanelaTagg.setObjectName("JanelaTagg")
        JanelaTagg.resize(727, 515)
        JanelaTagg.setMinimumSize(QtCore.QSize(727, 515))
        self.centralwidget = QtWidgets.QWidget(parent=JanelaTagg)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.abasWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.abasWidget.setObjectName("abasWidget")
        self.abaRelatorio = QtWidgets.QWidget()
        self.abaRelatorio.setObjectName("abaRelatorio")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.abaRelatorio)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.relatorio_titulo = QtWidgets.QLabel(parent=self.abaRelatorio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relatorio_titulo.sizePolicy().hasHeightForWidth())
        self.relatorio_titulo.setSizePolicy(sizePolicy)
        self.relatorio_titulo.setMinimumSize(QtCore.QSize(0, 50))
        self.relatorio_titulo.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.relatorio_titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.relatorio_titulo.setObjectName("relatorio_titulo")
        self.verticalLayout_3.addWidget(self.relatorio_titulo)
        self.widget = QtWidgets.QWidget(parent=self.abaRelatorio)
        self.widget.setObjectName("widget")
        self.relatorio_inputSelecaoPasta = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.relatorio_inputSelecaoPasta.setGeometry(QtCore.QRect(0, 20, 420, 31))
        self.relatorio_inputSelecaoPasta.setTabChangesFocus(False)
        self.relatorio_inputSelecaoPasta.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.relatorio_inputSelecaoPasta.setObjectName("relatorio_inputSelecaoPasta")
        self.relatorio_botaoSelecaoPasta = QtWidgets.QPushButton(parent=self.widget)
        self.relatorio_botaoSelecaoPasta.setGeometry(QtCore.QRect(400, 20, 121, 31))
        self.relatorio_botaoSelecaoPasta.setObjectName("relatorio_botaoSelecaoPasta")
        self.relatorio_checkboxArquivoUnico = QtWidgets.QCheckBox(parent=self.widget)
        self.relatorio_checkboxArquivoUnico.setGeometry(QtCore.QRect(0, 70, 281, 20))
        self.relatorio_checkboxArquivoUnico.setObjectName("relatorio_checkboxArquivoUnico")
        self.relatorio_labelSelecaoPasta = QtWidgets.QLabel(parent=self.widget)
        self.relatorio_labelSelecaoPasta.setGeometry(QtCore.QRect(0, 0, 121, 16))
        self.relatorio_labelSelecaoPasta.setObjectName("relatorio_labelSelecaoPasta")
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.abaRelatorio)
        self.widget_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.relatorio_botaoGerar = QtWidgets.QPushButton(parent=self.widget_5)
        self.relatorio_botaoGerar.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.relatorio_botaoGerar.setObjectName("relatorio_botaoGerar")
        self.relatorio_labelObs = QtWidgets.QLabel(parent=self.widget_5)
        self.relatorio_labelObs.setGeometry(QtCore.QRect(0, 50, 401, 16))
        self.relatorio_labelObs.setObjectName("relatorio_labelObs")
        self.gridLayout.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_2.raise_()
        self.widget.raise_()
        self.relatorio_titulo.raise_()
        self.abasWidget.addTab(self.abaRelatorio, "")
        self.abaEtiquetador = QtWidgets.QWidget()
        self.abaEtiquetador.setObjectName("abaEtiquetador")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.abaEtiquetador)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.etiquetador_titulo = QtWidgets.QLabel(parent=self.abaEtiquetador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etiquetador_titulo.sizePolicy().hasHeightForWidth())
        self.etiquetador_titulo.setSizePolicy(sizePolicy)
        self.etiquetador_titulo.setMinimumSize(QtCore.QSize(0, 50))
        self.etiquetador_titulo.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.etiquetador_titulo.setObjectName("etiquetador_titulo")
        self.verticalLayout_4.addWidget(self.etiquetador_titulo)
        self.widget_3 = QtWidgets.QWidget(parent=self.abaEtiquetador)
        self.widget_3.setObjectName("widget_3")
        self.etiquetador_labelSelecaoArquivo = QtWidgets.QLabel(parent=self.widget_3)
        self.etiquetador_labelSelecaoArquivo.setGeometry(QtCore.QRect(0, 0, 131, 16))
        self.etiquetador_labelSelecaoArquivo.setObjectName("etiquetador_labelSelecaoArquivo")
        self.etiquetador_inputSelecaoArquivo = QtWidgets.QPlainTextEdit(parent=self.widget_3)
        self.etiquetador_inputSelecaoArquivo.setGeometry(QtCore.QRect(0, 20, 401, 31))
        self.etiquetador_inputSelecaoArquivo.setTabChangesFocus(False)
        self.etiquetador_inputSelecaoArquivo.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.etiquetador_inputSelecaoArquivo.setObjectName("etiquetador_inputSelecaoArquivo")
        self.etiquetador_botaoSelecaoArquivo = QtWidgets.QPushButton(parent=self.widget_3)
        self.etiquetador_botaoSelecaoArquivo.setGeometry(QtCore.QRect(400, 20, 121, 31))
        self.etiquetador_botaoSelecaoArquivo.setObjectName("etiquetador_botaoSelecaoArquivo")
        self.etiquetador_labelSelecaoMedicoes = QtWidgets.QLabel(parent=self.widget_3)
        self.etiquetador_labelSelecaoMedicoes.setGeometry(QtCore.QRect(0, 70, 131, 16))
        self.etiquetador_labelSelecaoMedicoes.setObjectName("etiquetador_labelSelecaoMedicoes")
        self.etiquetador_inputSelecaoMedicoes = QtWidgets.QPlainTextEdit(parent=self.widget_3)
        self.etiquetador_inputSelecaoMedicoes.setGeometry(QtCore.QRect(0, 90, 401, 31))
        self.etiquetador_inputSelecaoMedicoes.setTabChangesFocus(False)
        self.etiquetador_inputSelecaoMedicoes.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.etiquetador_inputSelecaoMedicoes.setObjectName("etiquetador_inputSelecaoMedicoes")
        self.etiquetador_botaoSelecaoMedicoes = QtWidgets.QPushButton(parent=self.widget_3)
        self.etiquetador_botaoSelecaoMedicoes.setGeometry(QtCore.QRect(400, 90, 121, 31))
        self.etiquetador_botaoSelecaoMedicoes.setObjectName("etiquetador_botaoSelecaoMedicoes")
        self.etiquetador_labelSelecaoData = QtWidgets.QLabel(parent=self.widget_3)
        self.etiquetador_labelSelecaoData.setGeometry(QtCore.QRect(530, 70, 211, 16))
        self.etiquetador_labelSelecaoData.setObjectName("etiquetador_labelSelecaoData")
        self.etiquetador_inputSelecaoData = QtWidgets.QDateEdit(parent=self.widget_3)
        self.etiquetador_inputSelecaoData.setGeometry(QtCore.QRect(530, 90, 151, 31))
        self.etiquetador_inputSelecaoData.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeAllCursor))
        self.etiquetador_inputSelecaoData.setReadOnly(False)
        self.etiquetador_inputSelecaoData.setCalendarPopup(True)
        self.etiquetador_inputSelecaoData.setObjectName("etiquetador_inputSelecaoData")
        self.etiquetador_labelAssinante = QtWidgets.QLabel(parent=self.widget_3)
        self.etiquetador_labelAssinante.setGeometry(QtCore.QRect(0, 140, 301, 16))
        self.etiquetador_labelAssinante.setObjectName("etiquetador_labelAssinante")
        self.etiquetador_inputAssinante = QtWidgets.QComboBox(parent=self.widget_3)
        self.etiquetador_inputAssinante.setGeometry(QtCore.QRect(0, 160, 201, 24))
        self.etiquetador_inputAssinante.setObjectName("etiquetador_inputAssinante")
        self.etiquetador_inputAssinante.addItem("")
        self.etiquetador_inputAssinante.addItem("")
        self.etiquetador_inputAssinante.addItem("")
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.abaEtiquetador)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.etiquetador_botaoGerar = QtWidgets.QPushButton(parent=self.widget_7)
        self.etiquetador_botaoGerar.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.etiquetador_botaoGerar.setObjectName("etiquetador_botaoGerar")
        self.etiquetador_labelObs = QtWidgets.QLabel(parent=self.widget_7)
        self.etiquetador_labelObs.setGeometry(QtCore.QRect(0, 50, 571, 16))
        self.etiquetador_labelObs.setObjectName("etiquetador_labelObs")
        self.gridLayout_2.addWidget(self.widget_7, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.abasWidget.addTab(self.abaEtiquetador, "")
        self.verticalLayout_2.addWidget(self.abasWidget)
        JanelaTagg.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=JanelaTagg)
        self.statusbar.setObjectName("statusbar")
        JanelaTagg.setStatusBar(self.statusbar)

        self.retranslateUi(JanelaTagg)
        self.abasWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(JanelaTagg)
        
        # Eventos
        
        self.abasWidget.tabBarClicked.connect(self.eventoTrocaAba)
        
        self.relatorio_botaoSelecaoPasta.clicked.connect(self.eventoSelecaoPasta)
        self.relatorio_botaoGerar.clicked.connect(self.eventoGerarRelatorio)
        
        self.etiquetador_botaoSelecaoArquivo.clicked.connect(self.eventoSelecaoArquivo)
        self.etiquetador_botaoSelecaoMedicoes.clicked.connect(self.eventoSelecaoMedicoes)
        self.etiquetador_botaoGerar.clicked.connect(self.eventoGerarEtiquetas)
        
        
    def eventoTrocaAba(self):
        self.etiquetador_inputSelecaoData.setDate(datetime.today())
        
        
    def eventoSelecaoMedicoes(self):
        self.etiquetador_inputSelecaoMedicoes.setPlainText("Aguarde...")
        arquivo = QtWidgets.QFileDialog.getOpenFileName(None, 'Selecione o arquivo medições com todos os pedidos atualizados...', filter="Arquivo Excel (*.xlsx *.xlsm)")
        self.caminhoMedicoes = arquivo[0]
        
        self.etiquetador_inputSelecaoMedicoes.setPlainText(self.caminhoMedicoes)
        
    
    def eventoSelecaoArquivo(self):
        self.etiquetador_inputSelecaoArquivo.setPlainText("Aguarde...")
        arquivo = QtWidgets.QFileDialog.getOpenFileName(None, 'Selecione o arquivo com todas CT-Es mescladas', filter="Arquivo PDF (*.pdf)")
        self.caminhoArquivo = arquivo[0]
        
        self.etiquetador_inputSelecaoArquivo.setPlainText(self.caminhoArquivo)
        
    
    def eventoGerarEtiquetas(self):
        data = self.etiquetador_inputSelecaoData.text()
        assinante = self.etiquetador_inputAssinante.currentText()
        
        match assinante:
            case "Michelle Correa Lisboa":
                char_assinante = 'M'
                
            case "Gustavo Carvalho Daquano":
                char_assinante = 'G'
                
            case "Ninguém (Deixar em branco)":
                char_assinante = 'nenhum'
                
        
        pastaDestino = str(QtWidgets.QFileDialog.getExistingDirectory(caption="Selecione a pasta onde serão salvos o(s) arquivo(s)..."))
        
        if gerarEtiquetas.main(char_assinante, data, self.caminhoArquivo, self.caminhoMedicoes, pastaDestino) == 0:
            QtWidgets.QMessageBox.information(None, 'Sucesso!', f'CT-Es etiquetadas e salvas na "{pastaDestino}"!')

    
    def eventoGerarRelatorio(self):
        localSalvamento = str(QtWidgets.QFileDialog.getExistingDirectory(caption="Selecione a pasta onde serão salvos o(s) arquivo(s)..."))
        
        gerarRelatorio.main(localSalvamento, self.pastaLeitor, self.relatorio_checkboxArquivoUnico.isChecked())
        QtWidgets.QMessageBox.information(None, 'Sucesso!', f'Relatório emitido na pasta: "{localSalvamento}"!')
    
    def eventoSelecaoPasta(self):
        # Abre seletor de pasta
        self.relatorio_inputSelecaoPasta.setPlainText("Aguarde...")
        pasta = str(QtWidgets.QFileDialog.getExistingDirectory(caption="Selecione a pasta onde estão os PDFs DHL..."))
        self.relatorio_inputSelecaoPasta.setPlainText(pasta)
        
        self.pastaLeitor = pasta
        
    

    def retranslateUi(self, JanelaTagg):
        _translate = QtCore.QCoreApplication.translate
        JanelaTagg.setWindowTitle(_translate("JanelaTagg", "Tagg – Etiquetador DHL"))
        self.relatorio_titulo.setText(_translate("JanelaTagg", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Gerar Relatório</span></p></body></html>"))
        self.relatorio_inputSelecaoPasta.setPlaceholderText(_translate("JanelaTagg", "Selecione a pasta para leitura dos CT-Es DHL"))
        self.relatorio_botaoSelecaoPasta.setText(_translate("JanelaTagg", "Selecionar Pasta"))
        self.relatorio_checkboxArquivoUnico.setText(_translate("JanelaTagg", "Gerar arquivo com todas as CT-Es (sem etiqueta)"))
        self.relatorio_labelSelecaoPasta.setText(_translate("JanelaTagg", "Seleção dos CT-Es:"))
        self.relatorio_botaoGerar.setText(_translate("JanelaTagg", "Gerar"))
        self.relatorio_labelObs.setText(_translate("JanelaTagg", "OBS: Após gerar você deve selecionar a pasta onde será salvo o(s) arquivo(s)"))
        self.abasWidget.setTabText(self.abasWidget.indexOf(self.abaRelatorio), _translate("JanelaTagg", "Gerador Relatório"))
        self.etiquetador_titulo.setText(_translate("JanelaTagg", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Etiquetador de CT-Es – DHL</span></p></body></html>"))
        self.etiquetador_labelSelecaoArquivo.setText(_translate("JanelaTagg", "Seleção dos CT-Es:"))
        self.etiquetador_inputSelecaoArquivo.setPlaceholderText(_translate("JanelaTagg", "Selecione a pasta ou arquivo único para leitura dos CT-Es DHL"))
        self.etiquetador_botaoSelecaoArquivo.setText(_translate("JanelaTagg", "Selecionar Pasta"))
        self.etiquetador_labelSelecaoMedicoes.setText(_translate("JanelaTagg", "Seleção dos Pedidos:"))
        self.etiquetador_inputSelecaoMedicoes.setPlaceholderText(_translate("JanelaTagg", "Selecione a planilha \"Medições DHL.xlsm\" mais atualizada"))
        self.etiquetador_botaoSelecaoMedicoes.setText(_translate("JanelaTagg", "Selecionar Planilha"))
        self.etiquetador_labelSelecaoData.setText(_translate("JanelaTagg", "Utilizar pedidos de qual data?"))
        self.etiquetador_labelAssinante.setText(_translate("JanelaTagg", "Quem irá assinar?"))
        self.etiquetador_inputAssinante.setItemText(0, _translate("JanelaTagg", "Michelle Correa Lisboa"))
        self.etiquetador_inputAssinante.setItemText(1, _translate("JanelaTagg", "Gustavo Carvalho Daquano"))
        self.etiquetador_inputAssinante.setItemText(2, _translate("JanelaTagg", "Ninguém (Deixar em branco)"))
        self.etiquetador_botaoGerar.setText(_translate("JanelaTagg", "Gerar"))
        self.etiquetador_labelObs.setText(_translate("JanelaTagg", "<html><head/><body><p>OBS: Após gerar você deve selecionar a pasta onde será salvo o arquivo com todas as <span style=\" font-weight:700;\">CT-Es etiquetadas</span></p></body></html>"))
        self.abasWidget.setTabText(self.abasWidget.indexOf(self.abaEtiquetador), _translate("JanelaTagg", "Etiquetador"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JanelaTagg = QtWidgets.QMainWindow()
    ui = Ui_JanelaTagg()
    ui.setupUi(JanelaTagg)
    JanelaTagg.show()
    sys.exit(app.exec())
